### ISSUE TITLE
Deprecation Warnings present when debug is off

### ISSUE THREAD

**Issue by arobsco** [adobe/reactor-turbine#132]
Deprecation warnings are being printed to console even with debug mode off/set to false.

Below change was made some time ago however doesn't look like its been used much until recently. 
https://github.com/adobe/reactor-turbine/blob/b68d3d4c139d73030f50e5e015534d23c399073e/src/logger.js#L108-L120

Expected behavior is that warnings are only printed to console with debug mode enabled. Otherwise they should be suppressed as per other logger functions.

![image](https://user-images.githubusercontent.com/18175536/129704545-707ae20c-9b6e-410a-93f4-630ae91eb720.png)

On a side note there doesn't appear to be any documentation around proposed deprecated functionality...

**Comment by arobsco** [comment]
This appears to have been intentional per #121 so happy to close it off if Adobe disagree that this should be changed.

Only thing to mention in relation is that this functionality change doesn't appear to have been referenced in any release notes which is why it has caught customers by surprise. (https://experienceleague.adobe.com/docs/experience-platform/tags/release-notes/current.html?lang=en)

**Comment by jkunz** [comment]
This is causing a lot of headaches with clients. Every few days someone on measure slack asks about it. For one of my clients, the error made them nearly remove Launch from the lower environments of the new site they are working on- it undermines the credibility of this new tool we're asking them to add. 
Since Adobe extensions are throwing the error (therefore making it show up nearly universally), can we please put this error behind debug mode?

**Comment by jeffreywalter** [comment]
Sorry ahead of time for the novel, but here’s some background:
There is a balance between too many deprecation warnings and so few that no one heeds them. By displaying the deprecation warning at every invocation, devs are now aware how often they are calling that function. If we made the warning once per page, no one would have incentive to change. I know…I’m a developer and that’s how lazy we are 😄  
For extension developers, it’s a matter of priority. If I don’t feel the pain, I will do something else that requires my attention. 
With moving deprecation warnings out of "warning" level, we've had multiple extensions already update to remove the deprecated method. This just would not have happened otherwise.

Howver, we’ve heard the feedback about the warnings and are considering options to keep the balance of urgency and annoyance. I can’t promise we’ll change anything in this specific case, but we definitely will take this into account for future actions.

We have a item prioritized to evaluate how we deprecate APIs in the future
